name: 'mattermost-registration'

services:
  mattermost-registration:
    image: ghcr.io/dpsg1312/mattermost-registration-by-domain:latest
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - stack.env

networks:
  proxy:
    external: true


